# Generated by Django 3.1.7 on 2021-04-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('fname', models.CharField(max_length=1000)),
                ('classname', models.IntegerField()),
                ('contact', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('-classname',),
            },
        ),
    ]
